### ISSUE TITLE
终端输出缺少第一个字母

### ISSUE THREAD

**Issue by padeny** [aitalk-app/aitalk#1]
执行aitalk命令，在终端打印的输出有时会缺少第一个字母，生成的talk文件中并没有少
![image](https://user-images.githubusercontent.com/15116448/230808892-32c2908a-09e4-4904-ac15-1f3bbceb34ed.png)

**Comment by shellfly** [comment]
这个呢，最新版还有问题吗

**Comment by padeny** [comment]
也没问题了
