### ISSUE TITLE
对话超出token长度限制后直接报错

### ISSUE THREAD

**Issue by padeny** [aitalk-app/aitalk#2]
对话上下文超出token长度限制后直接报错，本地没有保存到文件
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15116448/230825355-5c24f33d-4154-4074-821d-d32f68b5189f.png">

**Comment by shellfly** [comment]
安装了最新版吗，这个问题应该在这个commit里修复了https://github.com/aitalk-app/aitalk/commit/04093b8384cdbab471e41bfed5a4f02a6c3f967b

**Comment by padeny** [comment]
嗯，拉最新的代码试了下没问题了

**Comment by shellfly** [comment]
👌
